version: "3.9"

services:
  stellar:
    image: stellar/quickstart
    environment:
      HORIZON_DB_URL: "${HORIZON_DB_URL}"
    volumes:
      - "./data:/opt/stellar"
      - stellar-data:/var/lib/postgresql/data  # Shared volume for database data
    ports:
      - "8000:8000"  # Horizon main HTTP port
      - "6060:6060"  # Horizon admin port
      - "11625:11625"  # Stellar-core peer node port
      - "11626:11626"  # Stellar-core main HTTP port
    
    restart: unless-stopped
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent storage for database data
    ports:
      - "5432:5432"  # Expose PostgreSQL port

volumes:
  data:  # Volume data persistent
  stellar-data:  # Shared volume for database data
  postgres-data:  # Persistent storage for database data
